# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "10 * * * *" #run each 10min
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Install the python version needed
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip tweepy
    - name: Execute Python Script # Run the functions.py on the repository root directory
      run: |
          python functions.py
